export const product = [
  {
    id: 1,
    imges: "/public/asset/01.jpg",
    spanse: "All level",
    titleing: "Digital Marketing Masterclass",
    pragragh: "Proposal indulged no do sociable he throwing settling",
    catrgyre: "Figma",
  },
  {
    id: 2,
    imges: "/public/asset/02.jpg",
    spanse: "Beginner",
    titleing: "Graphic Design Masterclass",
    pragragh: "Proposal indulged no do sociable he throwing settling",
    catrgyre: "Figma",
  },
  {
    id: 3,
    imges: "/public/asset/03.jpg",
    spanse: "All level",
    titleing: "Create a Design System in Figma",
    pragragh: "Proposal indulged no do sociable he throwing settling",
    catrgyre: "Figma",
  },
  {
    id: 4,
    imges: "/public/asset/04.jpg",
    spanse: "Beginner ",
    titleing: "Learn Invision",
    pragragh: "Proposal indulged no do sociable he throwing settling",
    catrgyre: "Invision",
  },
  {
    id: 5,
    imges: "/public/asset/05.jpg",
    spanse: "All level",
    titleing: "The Complete Web Development in python",
    pragragh: "Proposal indulged no do sociable he throwing settling",
    catrgyre: "Invision",
  },
  {
    id: 6,
    imges: "/public/asset/06.jpg",
    spanse: "Beginner",
    titleing: " Angular - The Complete Guider",
    pragragh: "Proposal indulged no do sociable he throwing settling",
    catrgyre: "Invision",
  },
  {
    id: 7,
    imges: "/public/asset/07.jpg",
    spanse: "All level",
    titleing: "Deep Learning with React-Native",
    pragragh: "Proposal indulged no do sociable he throwing settling",
    catrgyre: "React-Native",
  },
  {
    id: 8,
    imges: "/public/asset/08.jpg",
    spanse: "Beginner",
    titleing: "Sketch from A to Z: for app designer",
    pragragh: "Proposal indulged no do sociable he throwing settling",
    catrgyre: "React-Native",
  },
  {
    id: 9,
    imges: "/public/asset/09.jpg",
    spanse: "All level",
    titleing: "JavaScript: Full Understanding",
    pragragh: "Proposal indulged no do sociable he throwing settling",
    catrgyre: "React-Native",
  },
  {
    id: 10,
    imges: "/public/asset/10.jpg",
    spanse: "Beginner",
    titleing: "Bootstrap 5 From Scratch",
    pragragh: "Proposal indulged no do sociable he throwing settling",
    catrgyre: "Bootstrap",
  },
  {
    id: 11,
    imges: "/public/asset/11.jpg",
    spanse: "All level",
    titleing: "Build Responsive Websites with HTML",
    pragragh: "Proposal indulged no do sociable he throwing settling",
    catrgyre: "Bootstrap",
  },
  {
    id: 12,
    imges: "/public/asset/12.jpg",
    spanse: "Beginner",
    titleing: "Build Websites with CSS",
    pragragh: "Proposal indulged no do sociable he throwing settling",
    catrgyre: "PHP",
  },
  {
    id: 13,
    imges: "/public/asset/13.jpg",
    spanse: "All level",
    titleing: "PHP with - CMS Project",
    pragragh: "Proposal indulged no do sociable he throwing settling",
    catrgyre: "PHP",
  },
];
